# fly.toml app configuration file generated for todo-backend-k8s on 2025-10-04T17:32:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-backend-k8s'
primary_region = 'fra'

[build]

[env]
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
