apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    labels:
        app: todo-backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: todo-backend
    template:
        metadata:
            labels:
                app: todo-backend
        spec:
            containers:
                - name: backend
                  image: todo-backend:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3002
                  env:
                      - name: PORT
                        value: "3002"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3002
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3002
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: todo-backend
    ports:
        - protocol: TCP
          port: 3002
          targetPort: 3002
    type: ClusterIP
